language: node_js

node_js:
  - "0.11"

before_script:
  - "npm install -g grunt"
  - "npm install"

script:
  - "NODE_ENVIRONMENT=test node --harmony `which grunt`"

notifications:
  email:
    - ram@hiddentao.com