branches:
  only:
  - master

language: node_js

node_js:
  - '4'
  - '5'
  - '6'

before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get -y --force-yes install rethinkdb

before_script:
  - rethinkdb --daemon

script:
  - npm run test-ci

after_success:
  if [ "${TRAVIS_NODE_VERSION}" = "4" ]; then node scripts/triggerDocSiteBuild.js; fi

notifications:
  email:
  - ram@hiddentao.com

env:
  global:
    secure: S0+kWx+F56zFvFtuoLYlu6BDMjc3U9OZruuCwSYV/aNLdIo/mtpuhYAMgzChlT5K4kVVF2bTeramFTZQ3nxKHKFZ34y8UW+Ju+ARH4oBzUsU+m0W+zKOsovtjLpSv3grS5yz5XqRiYMxJQFlGHdQjqX1/jDeA0KdkQbaLMVktak=

